name: Test Features

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - texlive
          - gregorio

    steps:
      - uses: actions/checkout@v4

      - name: Test Features
        uses: devcontainers/action@v1
        with:
          features-namespace: aiscgre-br/devcontainer-features
          base-path-to-features: ./src
          test-features: true
